import { emptyDraft, type Draft } from './prompt'
export interface Template {id:string;title:string;category:string;description:string;emoji:string;color:string;model:'gemini'|'gpt';image?:string;author?:string;source?:string;repository?:string;values:Partial<Draft['values']>;ratio:string}
const nano='https://github.com/YouMind-OpenLab/awesome-nano-banana-pro-prompts'
const gpt='https://github.com/YouMind-OpenLab/awesome-gpt-image-2'
export const templates:Template[]=[
{id:'cloud-cat',title:'把小猫装进好心情',category:'可爱角色',description:'毛绒质感 · 柔和日光 · 治愈系',emoji:'🐈',color:'#f6ede3',model:'gemini',ratio:'1:1',values:{subject:'一只戴着天空蓝耳机的奶油色小猫，闭着眼睛听音乐，圆圆的脸颊和小小的粉色鼻子',scene:'坐在浅色木桌上，背景是虚化的春日花园，安静、轻松又治愈',style:'精致的 3D 毛绒玩偶，圆润比例，细腻柔软的绒毛，克制的可爱感',composition:'平视中景，主体居中，完整展示耳朵和耳机，四周保留呼吸感',lighting:'左上方柔和的自然日光，轻盈阴影，奶油白、天空蓝与少量粉色',constraints:'只出现一只猫，耳机结构完整；不添加多余肢体、角色、品牌标识或水印'}},
{id:'product',title:'一件产品，一束好光',category:'商业摄影',description:'电商主图 · 材质细节 · 自然投影',emoji:'🧴',color:'#e7eeea',model:'gpt',ratio:'3:4',values:{subject:'一瓶透明玻璃香氛，瓶内是浅琥珀色液体，瓶盖为拉丝银色金属',scene:'极简摄影棚，浅灰背景与细腻石材台面',style:'高端商业静物摄影，忠实呈现玻璃折射和金属质感',composition:'产品占画面高度约三分之二，略偏右；左侧留出干净空间',lighting:'左侧大面积柔光，右侧微弱轮廓光，自然接触阴影',constraints:'瓶身形状对称，液面平整；不虚构品牌、文字或认证标识'}},
{id:'quote',title:'留一句值得记住的话',category:'海报排版',description:'人物引言卡 · 清晰层级 · 大幅留白',emoji:'💬',color:'#f0e6d8',model:'gemini',ratio:'16:9',image:'quote.jpg',author:'Nicolechan',source:'https://x.com/stark_nico99/status/1991718646570426763',repository:nano,values:{subject:'一张人物与引言组合的横版编辑设计卡片',scene:'深棕色背景，人物边缘自然融入底色',style:'沉静的杂志排版，浅金色衬线文字',composition:'左侧三分之一放人物肖像，右侧三分之二放引言，正文下方设置较小署名',text:'让好奇心，带你去更远的地方。\n— 创作者',constraints:'仅使用给定文案，不增加虚构名人署名。文字完整、边距一致。',reference:'上传一张已获授权的肖像作为人物参考；保留其面部特征'}},
{id:'bento',title:'产品信息，也可以很美',category:'信息设计',description:'Bento 网格 · 玻璃卡片 · 产品叙事',emoji:'🧊',color:'#e4ecf8',model:'gemini',ratio:'16:9',image:'bento.png',author:'Mansi Sanghani',source:'https://x.com/MansiSanghani1/status/2013550795224961492',repository:nano,values:{subject:'一张展示无线耳机的产品信息图，包含一个主视觉和四张信息卡',scene:'清透浅蓝背景，柔和玻璃反射',style:'半透明玻璃卡片，细边框和自然层次',composition:'横向非对称 Bento 网格，产品主视觉占左侧四成，信息卡在右侧对齐',lighting:'明亮柔光，蓝白主色调',text:'随心聆听\n舒适佩戴\n轻便随行\n清晰通话\n简洁操控',constraints:'不要编造续航、认证、芯片或性能参数；使用提供的文案，不添加其他文字'}},
{id:'exploded',title:'看见设计的每一层',category:'产品设计',description:'爆炸视图 · 工业质感 · 结构关系',emoji:'🥽',color:'#e9e6f7',model:'gpt',ratio:'3:4',image:'exploded.jpg',author:'wory＠ホッピング中',source:'https://x.com/wory37303852/status/2045925660401795478',repository:gpt,values:{subject:'一副概念 VR 头显的分层爆炸视图，外壳、镜片和头带依次分离',scene:'干净的浅紫色摄影棚背景',style:'精细工业设计 3D 渲染，哑光塑料、玻璃与织物呈现不同质感',composition:'三组部件沿同一垂直轴排列，彼此保持合理间距，预留顶部标题区域',lighting:'大型柔光箱照明，边缘有柔和蓝紫色轮廓光',text:'以结构，探索想象',constraints:'呈现概念设计，不声称是真实产品内部结构；不添加品牌和未经证实的硬件参数'}},
{id:'food-map',title:'沿着美味，逛一座城',category:'插画地图',description:'手绘水彩 · 城市漫游 · 图文布局',emoji:'🍜',color:'#f9edd6',model:'gpt',ratio:'3:4',image:'map.jpg',author:'皮皮特',source:'https://x.com/mm_zzm44854/status/2045861258520568230',repository:gpt,values:{subject:'一张成都美食主题的装饰性漫游地图，用插画表现火锅、盖碗茶、冰粉和担担面',scene:'带有纸张纹理的浅米色底，装饰性的街道线条串联食物',style:'手绘水彩与细钢笔线稿，活泼亲切的小插画',composition:'上方标题，中间四组美食节点，右下角放小图例；图标与标签一一对应',lighting:'朱红、竹绿和茶褐色，温暖的纸面质感',text:'成都·美味漫游\n火锅\n盖碗茶\n冰粉\n担担面\n创意示意，非导航地图',constraints:'不要虚构餐馆地址或精确地理位置；避免文字重叠'}},
{id:'room',title:'阳光住进我的房间',category:'空间设计',description:'生活方式 · 空间层次 · 家居摄影',emoji:'🛋️',color:'#e9eedb',model:'gemini',ratio:'4:3',values:{subject:'一间小而明亮的客厅，奶油色布艺沙发、橡木茶几、一盆绿植',scene:'春日午后，窗外有树影，空间温馨而整洁',style:'真实室内摄影，保留亚麻织物和天然木材纹理',composition:'从入口平视客厅，使用自然透视，家具比例协调',lighting:'阳光从画面左侧窗户进入，在地板形成柔和树影',constraints:'家具保持完整且符合实际尺度，不出现重复家具或扭曲墙面'}},
{id:'sticker',title:'今天也是元气小狗',category:'可爱角色',description:'表情贴纸 · 角色一致性 · 九宫格',emoji:'🐶',color:'#f8e8e9',model:'gpt',ratio:'1:1',values:{subject:'同一只白色圆脸小狗的九种表情：开心、困倦、惊讶、害羞、委屈、加油、满足、疑惑、挥手',scene:'纯白背景，每个角色独立呈现',style:'柔和扁平插画，粗细一致的暖灰轮廓线，淡粉色脸颊',composition:'均匀 3×3 网格，每格一只小狗，留白一致，角色不触碰边缘',lighting:'平面色块，少量柔和阴影',constraints:'九格角色保持同样的耳朵、毛色、体型和线条风格，不出现文字'}}]
export function fromTemplate(t:Template):Draft{
 const d=emptyDraft();d.title=t.title;d.model=t.model;d.ratio=t.ratio;Object.assign(d.values,t.values);return d
}
